@BasarsoftInternship_HostAddress = http://localhost:5036

GET {{BasarsoftInternship_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{BasarsoftInternship_HostAddress}}/Point/
Accept: application/json